name: Generate Sitemap

on:
  push:
    branches:
      - main # 如果主分支不是 main，修改这里

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许 action 提交更改

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 根据需要调整 Node.js 版本

      - name: Create sitemap generation script
        run: |
          mkdir -p .github/scripts
          cat << 'EOF' > .github/scripts/generate-sitemap.js
          const fs = require('fs');
          const path = require('path');

          const BASE_URL = process.env.BASE_URL;
          if (!BASE_URL) {
            console.error("错误：未设置 BASE_URL 环境变量。请在 GitHub Secrets 中设置 SITE_BASE_URL 并在 workflow 中正确传递。");
            process.exit(1);
          }

          const articlesDir = path.join(process.cwd(), 'articles', 'content');
          const sitemapPath = path.join(process.cwd(), 'sitemap.xml');

          let urls = [];

          // 1. 添加主页 (index.html)
          urls.push({
            loc: \`\${BASE_URL}/\`, // 假设 index.html 对应网站根目录
            changefreq: 'daily',
            priority: '1.0',
            lastmod: new Date().toISOString().split('T')[0] // 使用当前日期作为最后修改日期
          });

          // 2. 从 articles/content/ 目录添加文章页面
          try {
            if (fs.existsSync(articlesDir)) {
              const articleFiles = fs.readdirSync(articlesDir).filter(file => file.endsWith('.html'));
              articleFiles.forEach(file => {
                const articleId = path.basename(file, '.html');
                const stats = fs.statSync(path.join(articlesDir, file));
                urls.push({
                  loc: \`\${BASE_URL}/article/\${articleId}\`, // 根据您的文章路由结构
                  changefreq: 'weekly',
                  priority: '0.8',
                  lastmod: stats.mtime.toISOString().split('T')[0] // 使用文件的实际修改日期
                });
              });
            } else {
              console.warn(\`警告：文章目录 '\${articlesDir}' 未找到。\`);
            }
          } catch (error) {
            console.error(\`读取文章目录时出错: \${error.message}\`);
          }

          // 3. 生成 sitemap.xml 内容
          const sitemapContent = \`<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
            \${urls.map(url => \`
            <url>
              <loc>\${url.loc}</loc>
              <changefreq>\${url.changefreq}</changefreq>
              <priority>\${url.priority}</priority>
              \${url.lastmod ? \`<lastmod>\${url.lastmod}</lastmod>\` : ''}
            </url>\`).join('')}
          </urlset>\`;

          try {
            fs.writeFileSync(sitemapPath, sitemapContent.trim());
            console.log(\`站点地图已成功生成于: \${sitemapPath}\`);
          } catch (error) {
            console.error(\`写入站点地图时出错: \${error.message}\`);
            process.exit(1);
          }
          EOF

      - name: Generate sitemap
        run: node .github/scripts/generate-sitemap.js
        env:
          BASE_URL: ${{ secrets.SITE_BASE_URL }}

      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: 自动生成 sitemap.xml"
          file_pattern: sitemap.xml # 确保只提交 sitemap.xml
          commit_user_name: GitHub Actions Bot # 可选
          commit_user_email: actions@github.com # 可选
          commit_author: GitHub Actions Bot <actions@github.com> # 可选
