      - name: Create sitemap generation script
        run: |
          mkdir -p .github/scripts
          cat << 'EOF' > .github/scripts/generate-sitemap.js
          // 将 require 改为 import
          import fs from 'fs';
          import path from 'path';

          const BASE_URL = process.env.BASE_URL;
          if (!BASE_URL) {
            console.error("错误：未设置 BASE_URL 环境变量。请在 GitHub Secrets 中设置 SITE_BASE_URL 并在 workflow 中正确传递。");
            process.exit(1);
          }

          const articlesDir = path.join(process.cwd(), 'articles', 'content');
          const sitemapPath = path.join(process.cwd(), 'sitemap.xml');

          let urls = [];

          urls.push({
            loc: `${BASE_URL}/`,
            changefreq: 'daily',
            priority: '1.0',
            lastmod: new Date().toISOString().split('T')[0]
          });

          try {
            if (fs.existsSync(articlesDir)) {
              const articleFiles = fs.readdirSync(articlesDir).filter(file => file.endsWith('.html'));
              articleFiles.forEach(file => {
                const articleId = path.basename(file, '.html');
                const stats = fs.statSync(path.join(articlesDir, file));
                urls.push({
                  loc: `${BASE_URL}/article/${articleId}`,
                  changefreq: 'weekly',
                  priority: '0.8',
                  lastmod: stats.mtime.toISOString().split('T')[0]
                });
              });
            } else {
              console.warn(`警告：文章目录 '${articlesDir}' 未找到。`);
            }
          } catch (error) {
            console.error(`读取文章目录时出错: ${error.message}`);
          }

          const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
            ${urls.map(url => `
            <url>
              <loc>${url.loc}</loc>
              <changefreq>${url.changefreq}</changefreq>
              <priority>${url.priority}</priority>
              ${url.lastmod ? `<lastmod>${url.lastmod}</lastmod>` : ''}
            </url>`).join('')}
          </urlset>`;

          try {
            fs.writeFileSync(sitemapPath, sitemapContent.trim());
            console.log(`站点地图已成功生成于: ${sitemapPath}`);
          } catch (error) {
            console.error(`写入站点地图时出错: ${error.message}`);
            process.exit(1);
          }
          EOF

      - name: Generate sitemap
        run: node .github/scripts/generate-sitemap.js
        env:
          BASE_URL: ${{ secrets.SITE_BASE_URL }}
